language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - ncftp
before_install:
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
install: 
- pip install -r requirements.txt
- npm install
script:
- npm run precommit
- make build
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = false ]; then ./deploy.sh; fi
env:
  global:
  - NODE_VERSION="5.7"
  - secure: IyB16lLUqGxpLytm4jW/3uBIAqML2ibdAgBYzt8VsIJdRs8KF5XYSg7wWGZsiNePeegZ9ZDRYAGpJ2Pcz3tCiZSQRwS/We3/QCFzEDZ4bpQT687V1kE5Q3T6FVULaRnmjNZYgl6Eu7JeK5NTlm7U5explVfWi40bdXxLuhABcsqMyh409+8QRS/CUKkWLll2EM54exUmcHEjouxHrIEvxWGfuAkOQN/XT+u/w2uXJ8A3Zq5F8EYHdMG7vccE1XYopHPKFeqRnjW77DRprqj++RnslSo/yf9UyhAWDDvy4tGEC0uRCAjPuzU0cMDxsHT3vU03Wsn+kl23O2YT91ZuTDjE64tPFLclnlF8fe2vf02RsnnNjBg6mv3S52wtDB8d9fZkyGdzo69uwvGDzCwRioIm+6HT375gQjgZnNmFCG7OPrTFC3dfVsp0dQXjAP9J7LHM/VVfCauqRzjj9vrk34b3Y53ix4hV7X5s3JpAGEtbWU5BpLefHkZfTBRXwTtNR62rO9/1eD3h5wrLpdwGCPKFWPUIgc3igoBHdDbQi8Y6u6xSeHLOt8CamqAE7nIUjKnqhNA0wS31KuOgmvXDeFqYbUJUmz8FJPSD88X6oWrNjDVwWEePR9UrXBimdrQurve7Tc9w0bkcSDRtuOL16gLzOmPuYN+NKnGEhSycspQ=
  - secure: V51RdKhQO7xce5Ot+FF2mLfVHY4CBRfaS7AsMQLMsfT51RLRUyaC4e2rIFxcx/N6TkMXtex0wmRdgIJBXJ0gjyof5GwK5ssx3EoL8e3Fv9XzD4A/X+oMeXWd5orztgeMSKP1CL9AJLdJiMgEpi8bQ2ZLVU22aqO+HCP9wFhoZOTGONiw5YyckQvoyzjcW8aIpq0du7ZPSJhbzwx5AgjOBxnLdwWRgaKXPmCH+mslnQCxYFzPbHNHKDpVg/2TkeLKz7OYLtQ6OLy4rzeSTFDpbo1bs3g/Kj/kx878l8+k0sCc5GMBF9Az5DG2Y3DpyxlCV9wY4qCEFVJW+WB+t8+has0Ux1BByeVEp/5zAuGh3guHHXmXTD6P3VPNF6C0MsHmd/acOl1mbsZyToGvMBOF+Um9c4xrg99k2lvShzFi0XQ0iIK2DHoHnsZrXJAvtdZJ67yaIT+RtdKWLRt8WcFoZvdy+xsxjECguSbIBh2iqFU6C15x5x3bAj964yFR9+24qFfgnv6cRII5YVNXd5kIRz0QPtnyMYtYYOhrrOncmfSymnb6aGXUXPSwokiyDdSM7hkkynPVts6bZwSx9E5vBZFWl94hv9uwSS8lNlUlUywosiHXyBBAUn40oLFW6rE2A4iV0NUu0WIJxORHbYxfD2I0YgqlhF8fDs5KyeEWVZY=
  - secure: WisHjRmO2ItvMUg/nFsg0ZKqo28+2F992stuNyCsvSlJZjTLFNDFogaVZui7Hxe9p1vcFmKFnml0Rs66+nhnsCVnJPFiDiJsPf1kRbgBtnpbywhN/fLVvYq5LGCxzypMJulOHrf2tlRmHP0f6o/y/3lx2dCBduR1p6EAr4ZSB6Zo9tGzt4pkkqj51hN5KblEaCNdc25hKRjcFzYqyN8zLdO7DWCo7wl3mvLeySuPmS+XYy9n0awH4CAEJOBzKGkbeZbLA+Uybb/0W52cv3oaXvJCAJ8B3O2qHh+unF6s15Xg/AS2fN811e5faD8UkOpgU/D5ceyv1Z/L7H7OikmnY16cNX8gd2vT6SslMoyjhXaQhbM0n9iv233fR1Ja0/WIo1cQgPFLQrOsU1PPnPvmvBEmSBZnrL4BtmKxjq3LM5crs1ZSe+ihd9zp7WIOy+alqkXY4+VcXtblvHdBsO1aUaMvNAqlKtHZxsmcINSprYI50ep4FrDn3i5mScrNZWKRU0LKpITpYn4mCs5lsYQvx/SdhYQKPQvn2OgR9zFkmYYo2i7BbXiCAQb5RATJx2XpnIX9IpvVYErD3wXucUAd8bhqfiN8g/VZpN/CLTdq+0aE0cG1xgnwvt+wTWzoyx+AovpsmNJHNJvx8rf2PkseoIy3W7eHCju7no4lhTYpOlo=
